<?php
    include('header.php'); 
?>
    
    <!--Main container sec start-->
    <div class="mainContainer">
        <div class="mt-5">
            <div class="top-header-title pt-4">
                    <h1><img src="../../assets/img/Privasy Policy.png" alt="cricket" style="margin-top:-15px; width:40px">Privacy Policy </h1>
                </div>
            <div class="privacypolicySec">
                <div class="container">
                    <div class="mt-lg-5 text-left">
                    <div class="termContent">
                        <p>Privacy policy forms part of our Website's Terms of Service, by accepting the Terms of Service on the registration page, you consent to provide sensitive personal data or personal information and are aware of the purpose of sharing such information. Registration procedure cannot be completed until information in the non-optional fields is provided. Certain additional personal information may be requested by ;<b><a href="<?= $base_url ?>" target="_blank">FSL11.com</a></b> for permitting you access to any Cash Games organized by.</p>
                       
                        <p><b><a href="https://fsl11.com"> FSL11.com</a></b> values the trust our users and customers place in us when they give us access to their Personal Information. The Privacy Policy describes how we work to maintain that trust and protect that information.</p>
                        
                        <p><b><a href="https://fsl11.com">FSL11.com</a></b> has created this Privacy Policy in order to describe its collection, use and disclosure of personal data you give to FSL11.com when you access or use FSL11 online and/or mobile services and websites.</p>
                        
                        <p>This Privacy Policy covers only data that we collect through the Site, and not any other data collection or processing, including, without limitation, the data collection practices of any affiliate or other third party, including any third-party operators of web pages to which the Site links, and any information that we collect offline or through any websites, products, or services that do not display a direct link to this Privacy Policy.</p>
                        <P><b><a href="https://fsl11.com">FSL11.com</a></b> may amend this Privacy Policy at any time. By using the Site or providing information to us following such changes, you will have accepted the amended Privacy Policy. FSL11.com will notify users via email and/or by posting a notice on FSL11 Site for 30 days prior to such use or by other means as required by law. Your Usage of website after posting notice shall………..</P>
                        <h4>
                        1. <u>Information Collected</u></h4>
                        <p>When you create an <b><a href="https://fsl11.com">FSL11.com</a></b>account, request information, subscribe for a service, participate in a game , post a rating or review, post a question or answer, upload content or otherwise actively send us data on our Site, we collect such data including, but not limited to, your <b>user name, password, first and last name, email address, telephone number (including mobile phone number), street address, gender, occupation, interests, messages you send to users</b>, and any other data included in a submitted profile or resume, including but not limited to application materials and answers to screener questions submitted to Users through FSL11. we will also collect payment information <b>(e.g., credit card number and related verification information)</b>.</p>
                        <p>
                        You may also create an account or log in to your FSL11.com account using third-party websites including, but not limited to, Facebook. If you do not already have an FSL11.com account but log in to FSL11.com using your Facebook account, this creates an FSL11.com account using the same email address used in your Facebook account. Facebook may also ask for your permission to share certain details with FSL11, including but not limited to your name, profile picture, public profile information and email address. If you agree to provide this information to FSL11, Facebook will authenticate you and redirect you to the Site. You have the ability to disable the connection between your Facebook account and your FSL11.com account at any time by accessing your privacy settings on your Facebook account. <b>PLEASE NOTE THAT YOUR RELATIONSHIP WITH FACEBOOK OR ANY OTHER THIRD-PARTY WEBSITE IS GOVERNED SOLELY BY YOUR AGREEMENT WITH SUCH THIRD-PARTY WEBSITE.</b></p>
                        <p>In addition, as part of the standard operation of the Site, <b><a href="https://fsl11.com">FSL11.com</a></b> may automatically collect and analyze information from your computer or mobile device, including, but not limited to, your browser type, operating system, IP address and the domain name from which you accessed the Site, and if you are accessing our Site with your mobile device, the type of mobile device. In addition, we may automatically record and analyze actions taken on the Site including, but not limited to, date and times of use, clicks, page views, the amount of time you spend on each page, and search queries. FSL11.com reserves the right to match your IP address (or any other information) with other information about you in any way permitted by applicable law. FSL11.com will store this information on its equipment or the equipment of third parties that FSL11.com has a relationship with for that purpose. If you create anFSL11.com account, information may be collected under your account email address.</p>
                        <p>If you access or use the Site on your mobile telephone or other mobile device, including tablets, we collect mobile device identifiers, including MAC Address, and IP Address. <b><a href="https://fsl11.com">FSL11.com</a></b> may create and assign to your device an identifier that is similar to an account number. We may collect the name you have associated with your device, device type, telephone number, country, and any other information you choose to provide, such as user name, geolocation or email address.</p>
                        <p>If you are anUsers,<b> <a href="https://fsl11.com">FSL11.com</a></b> may request that you provide certain personal information to FSL11.com in order to verify your account. This information includes, but is not limited to your Users Identification & Password Formation will be used for internal purposes only, subject to any request by law enforcement or a court order.</p>
                        <h4>2.<u> Limitation of Use or Disclosure of Personal Data</u></h4>
                        <p>When a Playercloses an account, the Player will no longer have access to any of the data which we provided under that account name, including but not limited to, search history, search preferences, and any other data associated with the account.<b><a href="https://fsl11.com"> FSL11.com</a></b> reserves the right to keep any materials in a closed account as necessary to preserve and protect its rights as allowed by law (for example, to preserve records of a dispute) or to comply with its obligations under local law (for example, to keep an email address). A closed account does not mean that all of the data isexpunged from the FSL11.com systems,</p>
                        <p>
                        Users may disable an account, however FSL11.com must preserve business records pertaining to that account to comply with its obligations under law.</p>
                        <h4>3.<u> Uses and Disclosures of Information</u></h4>
                        <p><b><a href="https://fsl11.com">FSL11.com</a></b> is committed to privacy of personal information provided by its customer, subscribers. FSL11.com is committed to the security of all information associated with our customers. We have security measures in place to attempt to protect against the loss, misuse and alteration of personal information under our control. Any personal information you provide will only be used for the purpose for which you have provided it and will not be added to any third party mailing list without your consent.We will not contact you unless you signup for our newsletter.</p>
                        <p><b><a href="https://fsl11.com">FSL11.com</a></b> may also share such information with third parties <b>(including operators of third-party websites and/or social networking sites)</b>  in order to show you targeted marketing ,advertisements and other content that has been customized for you.</p>
                        <h4>4. <u>Transfer of Data to Third Parties</u></h4>
                        <p>We may use other companies, including affiliates and third parties, to perform services in connection with our operations, and to improve the Site and our other products and services. These third parties may include (but are not limited to) service providers and vendors.</p>
                        <p>
                        In the course of providing these services, those companies may have access to Personal Information, and such Personal Information may be transferred to other countries. Those companies are contractually required to treat such Personal Information in accordance with this Privacy Policy. Please also be aware that we may use third-party cloud service providers that provide hosting, data storage and other services pursuant to standard terms and conditions that may be nonnegotiable; these service providers have informed us or the general public that they apply security measures they consider adequate for the protection of information within their system, or they have a general reputation for applying such measures. However, we will not be liable (to the fullest extent permitted by law) for any damages that may result from the misuse of any information, including Personal Information, by these companies.</p>
                        <p>You may also use certain third-party sites or services that you link to from FSL11 Site. In such cases, all information you provide to a third party is provided to that third party and not to FSL11, and is subject to the third party’s privacy policy and terms of service. Please see the section below titled Links to Third-Party Sites for more information.</p>
                        <h4>5. <u>Cookies</u></h4>
                        <p>“Cookies” are small pieces of information that are stored by your browser on your computer’s hard drive. Please see our cookie policy for further information regarding FSL11 use of Cookies.</p>
                        <h4>6.<u>Links to Third-Party Sites</U></h4>
                        <p>The Site may make available links to other websites. When you click on such links, you may leave our Site. The Site may also make available Company Pages, which may contain information provided by third-party Users.<strong> WE ARE NOT RESPONSIBLE FOR THE INFORMATION COLLECTION, USE, DISCLOSURE OR OTHER PRIVACY PRACTICES OF ANY THIRD PARTY, INCLUDING OUR AFFILIATES, THIRD-PARTY SERVICE PROVIDERS, ANY USERSS (INCLUDING ANY USERS THAT PROVIDES A COMPANY PAGE), ANY THIRD-PARTY SOCIAL MEDIA PLATFORM, ANY THIRD PARTY MAKING AVAILABLE THE DEVICES OR OPERATING SYSTEMS FOR WHICH THE SITE IS AVAILABLE, AND ANY THIRD PARTY OPERATING ANY WEBSITE TO WHICH THE SITE CONTAINS A LINK. YOU MAY HAVE RIGHTS DIRECTLY ENFORCEABLE AGAINST THESE THIRD PARTIES SO YOU SHOULD CONSIDER THEIR PRIVACY POLICIES TO LEARN MORE.</strong></p>
                        <h4>7. <u>Opting Out</u></h4>
                        <p>If you no longer want to receive promotional materials from us based upon your Personal Information, going forward, you may opt out of receiving such marketing related messages by sending an email to opt-out at support@FSL11.com. Please note that we may still send other messages to you, such as administrative messages. We will try to comply with your request as soon as reasonably practicable.</p>

                  </div>
                    </div>
                </div>
               
            </div>
        </div>



    </div>
    <!--Main container sec end-->
<?php include('footerHome.php'); ?>